apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: etcd
spec:
  serviceName: etcd-headless
  replicas: {{ .Values.etcd.replicas | default 3 }}
  selector:
    matchLabels:
      app: etcd
  template:
    metadata:
      labels:
        app: etcd
    spec:
      resources:
        requests:
          cpu: "3"
          memory: "8Gi"
        limits:
          cpu: "4"
          memory: "16Gi"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: etcd
              topologyKey: "kubernetes.io/hostname"
      securityContext:
          fsGroup: 1001
      containers:
        - name: etcd
          image: {{ .Values.etcd.image }} 
          env:
            - name: ALLOW_NONE_AUTHENTICATION
              value: "no"
            - name: ETCD_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: etcd-root-secret
                  key: root-password
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: ETCD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: ETCD_INITIAL_ADVERTISE_PEER_URLS
              value: "http://$(POD_NAME).etcd-headless.default.svc.cluster.local:2380"
            - name: ETCD_ADVERTISE_CLIENT_URLS
              value: "http://$(POD_NAME).etcd-headless.default.svc.cluster.local:2379"
            - name: ETCD_LISTEN_PEER_URLS
              value: "http://0.0.0.0:2380"
            - name: ETCD_LISTEN_CLIENT_URLS
              value: "http://0.0.0.0:2379"
            - name: ETCD_INITIAL_CLUSTER
              value: "etcd-0=http://etcd-0.etcd-headless.default.svc.cluster.local:2380,etcd-1=http://etcd-1.etcd-headless.default.svc.cluster.local:2380,etcd-2=http://etcd-2.etcd-headless.default.svc.cluster.local:2380"
            - name: ETCD_INITIAL_CLUSTER_TOKEN
              value: "etcd-cluster-1"
            - name: ETCD_INITIAL_CLUSTER_STATE
              value: "new"
            - name: ETCD_QUOTA_BACKEND_BYTES
              value: "17179869184"  # 16 GiB (in bytes)
            - name: ETCD_AUTO_COMPACTION_MODE
              value: "periodic"
            - name: ETCD_AUTO_COMPACTION_RETENTION
              value: "15m"
            - name: ETCD_ELECTION_TIMEOUT
              value: "5000"
            - name: ETCD_HEARTBEAT_INTERVAL
              value: "500"
          ports:
            - containerPort: 2379
            - containerPort: 2380
          volumeMounts:
            - name: data
              mountPath: /bitnami/etcd
          securityContext:
            runAsUser: 1001
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.etcd.storage.size | default "20Gi" }}

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: etcd-pdb
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: etcd